package com.m4x4.mixtapes.item;

import com.m4x4.mixtapes.Base.ArmorMaterials;
import com.m4x4.mixtapes.maxs_mixtapes;
import com.m4x4.mixtapes.sound.MMSongs;
import com.m4x4.mixtapes.tabs.MMDiscTab;
import com.m4x4.mixtapes.tabs.MMItemTab;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.*;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class MMItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, maxs_mixtapes.MODID);

    // Items
    public static final RegistryObject<Item> blockman = ITEMS.register("blockman", () -> new MMBlockmanUsage(new Item.Properties().tab(MMItemTab.instance)));
    public static final RegistryObject<Item> blank_tape = ITEMS.register("blank_tape", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.RARE), "A time machine on the shoulders of memories"));

    //// Cassettes
    //public static final RegistryObject<Item> TestCassette = ITEMS.register("testcassette", () -> new MMCassetteItem(8, MMSongs.TEST_SOUND, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3060, "Test Cassette for MM"));

    // Update 1
    public static final RegistryObject<Item> cassette_agent_rainbow = ITEMS.register("cassette_agent_rainbow", () -> new MMCassetteItem(8, MMSongs.HCAS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5140, "And I am in sound mind"));
    public static final RegistryObject<Item> cassette_virginia = ITEMS.register("cassette_virginia", () -> new MMCassetteItem(8, MMSongs.DOLL_HOUSE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3460, "\"It's okay... I see you.\""));
    public static final RegistryObject<Item> cassette_allen = ITEMS.register("cassette_allen", () -> new MMCassetteItem(8, MMSongs.BOTP, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4820, "\"Flawed but fixable...\""));
    public static final RegistryObject<Item> cassette_max = ITEMS.register("cassette_max", () -> new MMCassetteItem(8, MMSongs.IS_IT_ME, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4340, "\"Oh yeah?! Try and stop me!\""));
    public static final RegistryObject<Item> cassette_lucas = ITEMS.register("cassette_lucas", () -> new MMCassetteItem(8, MMSongs.MATB, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3920, "\"I noticed and I notice it again\""));
    public static final RegistryObject<Item> cassette_rose_mary = ITEMS.register("cassette_rose_mary", () -> new MMCassetteItem(8, MMSongs.WIT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3160, "\"Power in the unconscious\""));
    public static final RegistryObject<Item> cassette_desmond = ITEMS.register("cassette_desmond", () -> new MMCassetteItem(8, MMSongs.HISTE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6020, "\"You loved me and thats all i ever cared about\""));
    public static final RegistryObject<Item> my_ordinary_life = ITEMS.register("cassette_my_ordinary_life", () -> new MMCassetteItem(8, MMSongs.MY_ORDINARY_LIFE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4620, "\"So high up, I'm near divine\""));
    public static final RegistryObject<Item> cassette_drunk = ITEMS.register("cassette_drunk", () -> new MMCassetteItem(8, MMSongs.DRUNK, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4300, "Where's my keys?"));
    public static final RegistryObject<Item> cassette_sss = ITEMS.register("cassette_sss", () -> new MMCassetteItem(8, MMSongs.SSS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4620, "\"Put a little more backbone into it!\""));
    public static final RegistryObject<Item> cassette_fnaf = ITEMS.register("cassette_fnaf", () -> new MMCassetteItem(8, MMSongs.FNAF, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3280, "\"We're waiting every night\""));
    public static final RegistryObject<Item> cassette_fnaf_1 = ITEMS.register("cassette_fnaf_1", () -> new MMCassetteItem(8, MMSongs.FIVE_LONG_NIGHTS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3760, "\"The friends are forever\""));
    public static final RegistryObject<Item> cassette_fmn = ITEMS.register("cassette_fmn", () -> new MMCassetteItem(8, MMSongs.FMN, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5000, "\"I may be missing my face, but even I could see this coming.\""));
    public static final RegistryObject<Item> cassette_jufab = ITEMS.register("cassette_jufab", () -> new MMCassetteItem(8, MMSongs.JUFAB, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4540, "\"Can't wait to meet you!\""));
    public static final RegistryObject<Item> cassette_eisoptrophobia = ITEMS.register("cassette_eisoptrophobia", () -> new MMCassetteItem(8, MMSongs.EISOP, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 1400, "\"This time, death cannot save you.\""));
    public static final RegistryObject<Item> cassette_djmm = ITEMS.register("cassette_djmm", () -> new MMCassetteItem(8, MMSongs.DJMM, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4240, "The best animatronic. period."));
    public static final RegistryObject<Item> cassette_golf_swamp = ITEMS.register("cassette_golf_swamp", () -> new MMCassetteItem(8, MMSongs.GOLFSWAMP, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3380, "\"Rock and Roll!\""));
    public static final RegistryObject<Item> cassette_roxanne = ITEMS.register("cassette_roxanne", () -> new MMCassetteItem(8, MMSongs.ROXANNE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3240, "She kinda bad tho"));
    public static final RegistryObject<Item> cassette_ych = ITEMS.register("cassette_ych", () -> new MMCassetteItem(8, MMSongs.YCH, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5340, "[TBD]"));
    public static final RegistryObject<Item> cassette_tiys = ITEMS.register("cassette_tiys", () -> new MMCassetteItem(8, MMSongs.TIYS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4720, "\"Why do I always get the weirdos...\""));
    public static final RegistryObject<Item> cassette_always_come_back = ITEMS.register("cassette_always_come_back", () -> new MMCassetteItem(8, MMSongs.ALWAYS_COME_BACK, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3180, "\"Until then don't you dare say that we are the same\""));
    public static final RegistryObject<Item> cassette_leave_me_behind = ITEMS.register("cassette_leave_me_behind", () -> new MMCassetteItem(8, MMSongs.LEAVE_ME_BEHIND, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4040, "\"Before I close the book, I always skip to the end.\""));
    public static final RegistryObject<Item> cassette_terrible_things = ITEMS.register("cassette_terrible_things", () -> new MMCassetteItem(8, MMSongs.TERRIBLE_THINGS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5520, "\"I'm undefeatable, I'm thriving\""));
    public static final RegistryObject<Item> cassette_im_sane = ITEMS.register("cassette_im_sane", () -> new MMCassetteItem(8, MMSongs.IM_SANE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3020, "\"HR wants a word with me, though IM the one craving Human Resources\""));
    public static final RegistryObject<Item> cassette_sandcastle_kingdoms = ITEMS.register("cassette_sandcastle_kingdoms", () -> new MMCassetteItem(8, MMSongs.SANDCASTLE_KINGDOMS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3680, "\"Maybe one day, you'll find a golden key.\""));
    public static final RegistryObject<Item> cassette_big_poppa = ITEMS.register("cassette_big_poppa", () -> new MMCassetteItem(8, MMSongs.BIG_POPPA, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5060, "R.I.P The GOAT of Hip-Hop"));
    public static final RegistryObject<Item> cassette_rfyl = ITEMS.register("cassette_rfyl", () -> new MMCassetteItem(8, MMSongs.RFYL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 1460, "Whoops, we forgot Thomas again"));
    public static final RegistryObject<Item> cassette_doors = ITEMS.register("cassette_doors", () -> new MMCassetteItem(8, MMSongs.DOTD, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4700, "This is just the beginning."));
    public static final RegistryObject<Item> cassette_guiding_light = ITEMS.register("cassette_guiding_light", () -> new MMCassetteItem(8, MMSongs.GUIDING_LIGHT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 1220, "\"You were almost there!\""));
    public static final RegistryObject<Item> cassette_here_i_come = ITEMS.register("cassette_here_i_come", () -> new MMCassetteItem(8, MMSongs.HERE_I_COME, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2960, "Ready or not..."));
    public static final RegistryObject<Item> cassette_here_i_come_2 = ITEMS.register("cassette_here_i_come_2", () -> new MMCassetteItem(8, MMSongs.HERE_I_COME_2, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3840, "You can't run, nor can you hide..."));
    public static final RegistryObject<Item> cassette_fbc = ITEMS.register("cassette_fbc", () -> new MMCassetteItem(8, MMSongs.FBC, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3420, "\"bro stop spamming lightning magic\""));
    public static final RegistryObject<Item> cassette_archetype = ITEMS.register("cassette_archetype", () -> new MMCassetteItem(8, MMSongs.ARCHETYPE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4860, "\"I like these calm moments before the storm\""));
    public static final RegistryObject<Item> cassette_battle_block = ITEMS.register("cassette_battle_block", () -> new MMCassetteItem(8, MMSongs.BBT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4840, "\"REALLY? WHAT TIPPED YOU OFF GENIUS?\""));
    public static final RegistryObject<Item> cassette_btd_5 = ITEMS.register("cassette_btd_5", () -> new MMCassetteItem(8, MMSongs.BTD5, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2340, "\"Got any Super Monkeys yet?\""));
    public static final RegistryObject<Item> cassette_gps = ITEMS.register("cassette_gps", () -> new MMCassetteItem(8, MMSongs.GPS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4100, "[TBD]"));
    public static final RegistryObject<Item> cassette_rod = ITEMS.register("cassette_rod", () -> new MMCassetteItem(8, MMSongs.ROD, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4960, "\"Blue. Cap.\""));
    public static final RegistryObject<Item> cassette_ig = ITEMS.register("cassette_ig", () -> new MMCassetteItem(8, MMSongs.IG, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6600, "\"Isaac and his mother lived alone in a small house on top of a hill...\""));
    public static final RegistryObject<Item> cassette_fl = ITEMS.register("cassette_fl", () -> new MMCassetteItem(8, MMSongs.FL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 1840, "\"Are you sure this is how you want this story to end Isaac?\""));
    public static final RegistryObject<Item> cassette_esc = ITEMS.register("cassette_esc", () -> new MMCassetteItem(8, MMSongs.ESC, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4160, "\"I'm gonna need a bit of ballage in my mouth right now\""));
    public static final RegistryObject<Item> cassette_tomcat = ITEMS.register("cassette_tomcat", () -> new MMCassetteItem(8, MMSongs.TOMCAT_DISPOSABLES, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 7140, "\"Nature i guess..\""));
    public static final RegistryObject<Item> cassette_normal_album = ITEMS.register("cassette_normal_album", () -> new MMCassetteItem(8, MMSongs.WBTTA, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5120, "\"Baby could you play along with me?\""));
    public static final RegistryObject<Item> cassette_okultra = ITEMS.register("cassette_okultra", () -> new MMCassetteItem(8, MMSongs.OKULTRA, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5900, "\"For what? For what?\""));
    public static final RegistryObject<Item> cassette_love_me_normally = ITEMS.register("cassette_love_me_normally", () -> new MMCassetteItem(8, MMSongs.LOVE_ME_NORMALLY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6900, "\"I suggest that we keep this informal\""));
    public static final RegistryObject<Item> cassette_puppeteer = ITEMS.register("cassette_puppeteer", () -> new MMCassetteItem(8, MMSongs.PUPPETEER, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3440, "\"Now dont be a fool go break all the rules!\""));
    public static final RegistryObject<Item> cassette_buckle = ITEMS.register("cassette_buckle", () -> new MMCassetteItem(8, MMSongs.BMP, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3040, "\"OHOHO THAT IS SO FIRE DUDE\""));
    public static final RegistryObject<Item> cassette_step_back = ITEMS.register("cassette_step_back", () -> new MMCassetteItem(8, MMSongs.STEPBACK, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3060, "\"Sounds like what gasoline smells like... good.\""));
    public static final RegistryObject<Item> cassette_toacw = ITEMS.register("cassette_toacw", () -> new MMCassetteItem(8, MMSongs.TOACW, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5300, "\"This was the moment in which Calamity reigned supreme.\""));
    public static final RegistryObject<Item> cassette_slime_god = ITEMS.register("cassette_slime_god", () -> new MMCassetteItem(8, MMSongs.RETURN_TO_SLIME, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5880, "\"Its purity is sullied by freshly absorbed muck and grime.\""));
    public static final RegistryObject<Item> cassette_scourge = ITEMS.register("cassette_scourge", () -> new MMCassetteItem(8, MMSongs.SOTU, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 9180, "\"Dont get cocky!\""));
    public static final RegistryObject<Item> cassette_universal_collapse = ITEMS.register("cassette_universal_collapse", () -> new MMCassetteItem(8, MMSongs.UNIVERSAL_COLLAPSE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5160, "\"It's not over yet, kid.\""));
    public static final RegistryObject<Item> cassette_jungle_dragon = ITEMS.register("cassette_jungle_dragon", () -> new MMCassetteItem(8, MMSongs.JUNGLE_DRAGON, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 10100, "\"The air is getting warmer around you.\""));
    public static final RegistryObject<Item> cassette_ghosts_n_stuff = ITEMS.register("cassette_ghosts_n_stuff", () -> new MMCassetteItem(8, MMSongs.GHOSTS_N_STUFF, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3760, "We are Professional Griefers"));
    public static final RegistryObject<Item> cassette_bad_end_theater = ITEMS.register("cassette_bad_end_theater", () -> new MMCassetteItem(8, MMSongs.BAD_END_THEATER, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 1980, "\"I've missed you my darling\""));
    public static final RegistryObject<Item> cassette_barbie = ITEMS.register("cassette_barbie", () -> new MMCassetteItem(8, MMSongs.BARBIE_GIRL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4040, "\"Anxiety, Panic Attacks, and OCD not included\""));
    public static final RegistryObject<Item> cassette_california = ITEMS.register("cassette_california", () -> new MMCassetteItem(8, MMSongs.CALI_GIRLS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4680, "\"Greetings, loved ones. Let's take a journey.\" (zen SHUT UP)"));
    public static final RegistryObject<Item> cassette_anarchy_rainbow = ITEMS.register("cassette_anarchy_rainbow", () -> new MMCassetteItem(8, MMSongs.ANARCHY_RAINBOW, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 7380, "\"You lip-sync, we drip ink\""));
    public static final RegistryObject<Item> cassette_amongus = ITEMS.register("cassette_amongus", () -> new MMCassetteItem(8, MMSongs.AMONGUS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3460, "amogus."));
    public static final RegistryObject<Item> cassette_furrymon = ITEMS.register("cassette_furrymon", () -> new MMCassetteItem(8, MMSongs.FURRYMON, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4240, "\"zwei's gonna be so pissed at me\""));
    public static final RegistryObject<Item> cassette_eternal_horizons = ITEMS.register("cassette_eternal_horizons", () -> new MMCassetteItem(8, MMSongs.EH, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3080, "\"...tear until it's done.\""));
    public static final RegistryObject<Item> cassette_tottfiy = ITEMS.register("cassette_tottfiy", () -> new MMCassetteItem(8, MMSongs.TOTTFIY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 8260, "\"Rip and...\""));
    public static final RegistryObject<Item> cassette_gym = ITEMS.register("cassette_gym", () -> new MMCassetteItem(8, MMSongs.GYMBATTLE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 7980, "Half of this games budget went into this song."));
    public static final RegistryObject<Item> cassette_steam_gardens = ITEMS.register("cassette_steam_gardens", () -> new MMCassetteItem(8, MMSongs.SG, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4700, "\"Now just keep sucking on it until we're all the way to the nut\""));
    public static final RegistryObject<Item> cassette_oot = ITEMS.register("cassette_oot", () -> new MMCassetteItem(8, MMSongs.OOT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3380, "\"A thing that does not change with time is a memory of younger days...\""));
    public static final RegistryObject<Item> cassette_island = ITEMS.register("cassette_island", () -> new MMCassetteItem(8, MMSongs.ISLAND, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2180, "\"Mathematical!\""));
    public static final RegistryObject<Item> cassette_potm = ITEMS.register("cassette_potm", () -> new MMCassetteItem(8, MMSongs.POTM, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2700, "\"Marceline, is it just you and me in the wreckage of the world?\""));
    public static final RegistryObject<Item> cassette_love_like_you = ITEMS.register("cassette_love_like_you", () -> new MMCassetteItem(8, MMSongs.LOVE_LIKE_YOU, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2880, "\"Let's only think about love!\""));
    public static final RegistryObject<Item> cassette_wild_side = ITEMS.register("cassette_wild_side", () -> new MMCassetteItem(8, MMSongs.WILD_SIDE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3180, "\"I'll be fine. It's always been like this\""));
    public static final RegistryObject<Item> cassette_wolf_and_rabbit = ITEMS.register("cassette_wolf_and_rabbit", () -> new MMCassetteItem(8, MMSongs.WAR, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4700, "\"In the game of love, the more desperate you are, the more you lose.\""));
    public static final RegistryObject<Item> cassette_box_15 = ITEMS.register("cassette_box_15", () -> new MMCassetteItem(8, MMSongs.BOX15, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4900, "\"Upupu~\""));
    public static final RegistryObject<Item> cassette_box_16 = ITEMS .register("cassette_box_16", () -> new MMCassetteItem(8, MMSongs.BOX16, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6640, "\"Mukuro Ikusaba, the 16th Student, lying hidden somewhere in this school...\""));
    public static final RegistryObject<Item> cassette_still_alive = ITEMS.register("cassette_still_alive", () -> new MMCassetteItem(8, MMSongs.STILL_ALIVE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3540, "\"Now you're thinking with pistons\""));
    public static final RegistryObject<Item> cassette_want_you_gone = ITEMS.register("cassette_want_you_gone", () -> new MMCassetteItem(8, MMSongs.WANT_YOU_GONE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2780, "\"I AM NOT A MORON\""));
    public static final RegistryObject<Item> cassette_betty = ITEMS.register("cassette_betty", () -> new MMCassetteItem(8, MMSongs.BETTY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2940, "\"Gravy, my mom loves you\""));
    public static final RegistryObject<Item> cassette_1thot_2thot = ITEMS.register("cassette_1thot_2thot", () -> new MMCassetteItem(8, MMSongs.OTTT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2640, "\"Because meme cassette quota\""));
    public static final RegistryObject<Item> cassette_cest_la_vie = ITEMS.register("cassette_cest_la_vie", () -> new MMCassetteItem(8, MMSongs.CEST_LA_VIE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3220, "That's life; such is life"));
    public static final RegistryObject<Item> cassette_good_morning = ITEMS.register("cassette_good_morning", () -> new MMCassetteItem(8, MMSongs.GOOD_MORNING, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3920, "\"You may be talented, but you're not Kanye West \""));
    public static final RegistryObject<Item> cassette_stronger = ITEMS.register("cassette_stronger", () -> new MMCassetteItem(8, MMSongs.STRONGER, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6260, "\"As a man I am flawed, but my music is perfect\""));
    public static final RegistryObject<Item> cassette_american_boy = ITEMS.register("cassette_american_boy", () -> new MMCassetteItem(8, MMSongs.AMERICAN_BOY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4800, "\"Hey! Don't mess with his funky flow!\""));
    public static final RegistryObject<Item> cassette_gravity = ITEMS.register("cassette_gravity", () -> new MMCassetteItem(8, MMSongs.GRAVITY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6220, "\"Irredeemable!\""));
    public static final RegistryObject<Item> cassette_addict = ITEMS.register("cassette_addict", () -> new MMCassetteItem(8, MMSongs.ADDICT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6320, "\"Maybe things won't be so terrible inside this hotel...\""));
    public static final RegistryObject<Item> cassette_insane = ITEMS.register("cassette_insane", () -> new MMCassetteItem(8, MMSongs.INSANE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3260, "\"You're never fully dressed without a smile!\""));
    public static final RegistryObject<Item> cassette_loser_baby = ITEMS.register("cassette_loser_baby", () -> new MMCassetteItem(8, MMSongs.LOSER_BABY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3520, "\"Play your card, be who you are\""));
    public static final RegistryObject<Item> cassette_cc = ITEMS.register("cassette_cc", () -> new MMCassetteItem(8, MMSongs.COTTON_CANDY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3420, "\"i have like a rainbow, in my vagina right now\""));
    public static final RegistryObject<Item> cassette_look_at_this = ITEMS.register("cassette_look_at_this", () -> new MMCassetteItem(8, MMSongs.LAT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3320, "\"Eaugh! Ever heard of mouthwash?! FUCK FAAAACCCEEEE!\""));
    public static final RegistryObject<Item> cassette_stolas = ITEMS.register("cassette_stolas", () -> new MMCassetteItem(8, MMSongs.YWBO, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4360, "\"I will never be far away from my special little starfire\""));
    public static final RegistryObject<Item> cassette_jlmw = ITEMS.register("cassette_jlmw", () -> new MMCassetteItem(8, MMSongs.JLMW, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4560, "\"Unless its me, and no matter what in this world i could give\""));
    public static final RegistryObject<Item> cassette_simoon = ITEMS.register("cassette_simoon", () -> new MMCassetteItem(8, MMSongs.SIMOON, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6780, "\"CHEESE AND RICE MOONY.\""));
    public static final RegistryObject<Item> cassette_god_race = ITEMS.register("cassette_god_race", () -> new MMCassetteItem(8, MMSongs.GR, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3200, "\"I CAN'T GO ONNNN!!! I WON'T ACHIEVE ANYTHINGGGGG!!\""));
    public static final RegistryObject<Item> cassette_anemoia = ITEMS.register("cassette_anemoia", () -> new MMCassetteItem(8, MMSongs.ANEMOIA, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2680, "\"HAAH!! Are you kidding?! I HATE THIS STUPID JOB!!!\""));
    public static final RegistryObject<Item> cassette_rocky = ITEMS.register("cassette_rocky", () -> new MMCassetteItem(8, MMSongs.SUNSET_ROSE_COCKTAIL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2320, "\"As wild waters, fast and free, it's your true name: Mississippi\""));
    public static final RegistryObject<Item> cassette_olive_branch = ITEMS.register("cassette_olive_branch", () -> new MMCassetteItem(8, MMSongs.OLIVE_BRANCH, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6320, "\"I don't want a sandwich!\""));
    public static final RegistryObject<Item> cassette_rasputin = ITEMS.register("cassette_rasputin", () -> new MMCassetteItem(8, MMSongs.RASPUTIN, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5360, "\"Chad vas... Bad\""));
    public static final RegistryObject<Item> cassette_djbcd = ITEMS.register("cassette_djbcd", () -> new MMCassetteItem(8, MMSongs.DJBCD, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3140, "\"Violence Required, Violence Aquired.\""));
    public static final RegistryObject<Item> cassette_eidolon_step = ITEMS.register("cassette_eidolon_step", () -> new MMCassetteItem(8, MMSongs.EIDOLON_STEP, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5900, "\"Goddamnit Deimos.\""));
    public static final RegistryObject<Item> cassette_adc = ITEMS.register("cassette_adc", () -> new MMCassetteItem(8, MMSongs.ADC, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2300, "\"Welcome to the Amazing Digital Circus!\""));
    public static final RegistryObject<Item> cassette_kratos = ITEMS.register("cassette_kratos", () -> new MMCassetteItem(8, MMSongs.GOD_OF_WAR, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4960, "\"Death can have me when it earns me.\""));
    public static final RegistryObject<Item> cassette_thunder = ITEMS.register("cassette_thunder", () -> new MMCassetteItem(8, MMSongs.THUNDER_ROLL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3640, "\"Street warrior, sushi chef, and the coolest lizard in the Peace Syndicate.\""));
    public static final RegistryObject<Item> cassette_highwire = ITEMS.register("cassette_highwire", () -> new MMCassetteItem(8, MMSongs.VITAL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4340, "\"Cause some mayhem out there~\""));
    public static final RegistryObject<Item> cassette_toxic_coffee = ITEMS.register("cassette_toxic_coffee", () -> new MMCassetteItem(8, MMSongs.TOXIC_COFFEE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4000, "\"Max after making the mod bootloop:\""));
    public static final RegistryObject<Item> cassette_virtual_insanity = ITEMS.register("cassette_virtual_insanity", () -> new MMCassetteItem(8, MMSongs.VIRTUAL_INSANITY, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4520, "\"Dancing, Walking, Rearranging Furniture.\""));
    public static final RegistryObject<Item> cassette_dreamland = ITEMS.register("cassette_dreamland", () -> new MMCassetteItem(8, MMSongs.DREAMLAND, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4880, "\"Does everybody live in a dreamland?\""));
    public static final RegistryObject<Item> cassette_like_that = ITEMS.register("cassette_like_that", () -> new MMCassetteItem(8, MMSongs.LIKE_THAT, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3560, "\"All told i got too bold, heart of gold\""));
    public static final RegistryObject<Item> cassette_final_duet = ITEMS.register("cassette_final_duet", () -> new MMCassetteItem(8, MMSongs.FINAL_DUET, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2660, "\"Why don't you enjoy a nice picnic with me? That always seems to cheer you up.\""));
    public static final RegistryObject<Item> cassette_tulips = ITEMS.register("cassette_tulips", () -> new MMCassetteItem(8, MMSongs.HOME_FOR_FLOWERS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 1880, "\"My thoughts will follow you into your dreams\""));
    public static final RegistryObject<Item> cassette_my_time = ITEMS.register("cassette_my_time", () -> new MMCassetteItem(8, MMSongs.MY_TIME, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6300, "Oyasumi"));
    public static final RegistryObject<Item> cassette_undertale = ITEMS.register("cassette_undertale", () -> new MMCassetteItem(8, MMSongs.UNDERTALE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 7640, "\"Despite everything, it's still you\""));
    public static final RegistryObject<Item> cassette_death_by_glamor = ITEMS.register("cassette_death_by_glamor", () -> new MMCassetteItem(8, MMSongs.DEATH_BY_GLAMOR, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2700, "\"THAT'S SHOW BUSINESS, BABY!\""));
    public static final RegistryObject<Item> cassette_sans = ITEMS.register("cassette_sans", () -> new MMCassetteItem(8, MMSongs.SANS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2920, "\"Human. I remember your'e minecrafts\""));
    public static final RegistryObject<Item> cassette_hopes_and_dreams = ITEMS.register("cassette_hopes_and_dreams", () -> new MMCassetteItem(8, MMSongs.FOHAD, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3240, "\"Quiet people piss me off...\""));
    public static final RegistryObject<Item> cassette_toriel = ITEMS.register("cassette_toriel", () -> new MMCassetteItem(8, MMSongs.YCACH, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2020, "\"I am Toriel, caretaker of the Ruins...\""));
    public static final RegistryObject<Item> cassette_scarlet_forest = ITEMS.register("cassette_scarlet_forest", () -> new MMCassetteItem(8, MMSongs.SCARLET_FOREST, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2580, "\"...2 minutes in jail and you've already started eating moss.\""));
    public static final RegistryObject<Item> cassette_a_cybers_world = ITEMS.register("cassette_a_cybers_world", () -> new MMCassetteItem(8, MMSongs.CYBERS_WORLD, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3340, "\"Potassium.\""));
    public static final RegistryObject<Item> cassette_safe_and_sound = ITEMS.register("cassette_safe_and_sound", () -> new MMCassetteItem(8, MMSongs.SAFEANDSOUND, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3880, "\"if my childhood had end credits\""));
    public static final RegistryObject<Item> cassette_asafeworld = ITEMS.register("cassette_asafeworld", () -> new MMCassetteItem(8, MMSongs.A_SAFE_WORLD, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3360, "I love Deltarune..."));
    public static final RegistryObject<Item> cassette_safe_and_cyber = ITEMS.register("cassette_safe_and_cyber", () -> new MMCassetteItem(8, MMSongs.SAC, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3360, "I love Capital Cities..."));
    public static final RegistryObject<Item> cassette_showdown = ITEMS.register("cassette_showdown", () -> new MMCassetteItem(8, MMSongs.SHOWDOWN, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2260, "\"I was just going to ask you to sell a gun to this child!\""));
    public static final RegistryObject<Item> cassette_guns_blazing = ITEMS.register("cassette_guns_blazing", () -> new MMCassetteItem(8, MMSongs.GUNS_BLAZING, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2600, "\"I AM REACHING UNHEARD LEVELS OF [ticked]. LEVEL 7 AT LEAST. YOUR FAULT.\""));
    public static final RegistryObject<Item> cassette_afterlife = ITEMS.register("cassette_afterlife", () -> new MMCassetteItem(8, MMSongs.AFTERLIFE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 7360, "H O W D Y ."));
    public static final RegistryObject<Item> cassette_mothers_love = ITEMS.register("cassette_mothers_love", () -> new MMCassetteItem(8, MMSongs.MOTHERS_LOVE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5720, "\"This is how it must be\""));
    public static final RegistryObject<Item> cassette_trial_by_fury = ITEMS.register("cassette_trial_by_fury", () -> new MMCassetteItem(8, MMSongs.TBF, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2180, "\"I hope you choke on the dust that will fill the underground\""));
    public static final RegistryObject<Item> cassette_ddyd = ITEMS.register("cassette_ddyd", () -> new MMCassetteItem(8, MMSongs.DDYD, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4660, "\"This next cassette seems very, very interesting.\""));
    public static final RegistryObject<Item> cassette_too_close = ITEMS.register("cassette_too_close", () -> new MMCassetteItem(8, MMSongs.TOO_CLOSE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3420, "\"I think its time for you to go\""));
    public static final RegistryObject<Item> cassette_efae = ITEMS.register("cassette_efae", () -> new MMCassetteItem(8, MMSongs.EFAE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4520, "\"It was the most cathartic kill I've ever done\""));
    public static final RegistryObject<Item> cassette_baka_mitai = ITEMS.register("cassette_baka_mitai", () -> new MMCassetteItem(8, MMSongs.BM, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5840, "\"You think of the yakuza as a way to die. To me... being yakuza... It's a way to live.\""));
    public static final RegistryObject<Item> cassette_sunset_breakfast = ITEMS.register("cassette_sunset_breakfast", () -> new MMCassetteItem(8, MMSongs.SUNSET_BREAKFAST, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 1680, "Growing older doesn't have to suck"));
    public static final RegistryObject<Item> cassette_cats_on_mars = ITEMS.register("cassette_cats_on_mars", () -> new MMCassetteItem(8, MMSongs.CATS_ON_MARS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3320, "\"Hey! Watch it!\""));
    public static final RegistryObject<Item> cassette_letter_to_my_brother = ITEMS.register("cassette_letter_to_my_brother", () -> new MMCassetteItem(8, MMSongs.LETTER_TO_MY_BROTHER, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4340, "Welcome home, Rome."));
    public static final RegistryObject<Item> cassette_after_dark = ITEMS.register("cassette_after_dark", () -> new MMCassetteItem(8, MMSongs.AFTER_DARK, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5160, "Rome's a simp"));
    public static final RegistryObject<Item> cassette_monster = ITEMS.register("cassette_monster", () -> new MMCassetteItem(8, MMSongs.MONSTER, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5140, "So edgy you could hurt yourself, be gentle Rome."));
    public static final RegistryObject<Item> cassette_ijam = ITEMS.register("cassette_ijam", () -> new MMCassetteItem(8, MMSongs.IJAM, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5080, "feelsstrongman"));
    public static final RegistryObject<Item> cassette_fmttm = ITEMS.register("cassette_fmttm", () -> new MMCassetteItem(8, MMSongs.FMTTM, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5320, "\"Shoot, that was my last quarter.\""));
    public static final RegistryObject<Item> cassette_goodbye_to_a_world = ITEMS.register("cassette_goodbye_to_a_world", () -> new MMCassetteItem(8, MMSongs.GTAW, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6620, "Remember me."));
    public static final RegistryObject<Item> cassette_a_realitys_grave = ITEMS.register("cassette_a_realitys_grave", () -> new MMCassetteItem(8, MMSongs.A_REALITYS_GRAVE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6360, "An adventure you'll never forget."));
    public static final RegistryObject<Item> cassette_rejuvenescencia = ITEMS.register("cassette_rejuvenescencia", () -> new MMCassetteItem(8, MMSongs.REJUV, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2160, "\"This is gonna make you feel better.\""));
    public static final RegistryObject<Item> cassette_wmtao = ITEMS.register("cassette_wmtao", () -> new MMCassetteItem(8, MMSongs.WMTAO, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2460, "\"Yeeeaah, let's move it, people!\""));
    public static final RegistryObject<Item> cassette_bow = ITEMS.register("cassette_bow", () -> new MMCassetteItem(8, MMSongs.BOW, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3600, "\"Let the Kitsune guide you.\""));
    public static final RegistryObject<Item> cassette_ghost = ITEMS.register("cassette_ghost", () -> new MMCassetteItem(8, MMSongs.GHOST, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3180, "\"I don't believe in animals, milk comes from the trees.\""));
    public static final RegistryObject<Item> cassette_wigglecore = ITEMS.register("cassette_wigglecore", () -> new MMCassetteItem(8, MMSongs.WIGGLECORE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3280, "\"I dodged\""));
    public static final RegistryObject<Item> cassette_if_we_fall = ITEMS.register("cassette_if_we_fall", () -> new MMCassetteItem(8, MMSongs.IF_WE_FALL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4840, "\"Blame it on the humans.\""));
    public static final RegistryObject<Item> cassette_kick_back = ITEMS.register("cassette_kick_back", () -> new MMCassetteItem(8, MMSongs.KICK_BACK, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3920, "\"If dreams do come true, I wanna hug a girl before I die\""));
    public static final RegistryObject<Item> cassette_vampire = ITEMS.register("cassette_vampire", () -> new MMCassetteItem(8, MMSongs.RIAV, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3740, "Gimme the music, this beat is too sick, I wanna drink til I get stupid!"));
    public static final RegistryObject<Item> cassette_lkr = ITEMS.register("cassette_lkr", () -> new MMCassetteItem(8, MMSongs.LKR, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5140, "[TBD]"));
    public static final RegistryObject<Item> cassette_lightsabers = ITEMS.register("cassette_lightsabers", () -> new MMCassetteItem(8, MMSongs.LIGHTSABERS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5680, "\"My flow non-binary, that mean it never miss\""));
    public static final RegistryObject<Item> cassette_pizza_time = ITEMS.register("cassette_pizza_time", () -> new MMCassetteItem(8, MMSongs.PIZZA_TIME, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4600, "Very..  A    N  I  C  E!!!"));
    public static final RegistryObject<Item> cassette_dan_tdm = ITEMS.register("cassette_dan_tdm", () -> new MMCassetteItem(8, MMSongs.STREET_FIGHTER, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4180, "\"Hey everyone! Dan here from The Diamond Minecart\""));
    public static final RegistryObject<Item> cassette_science_blaster = ITEMS.register("cassette_science_blaster", () -> new MMCassetteItem(8, MMSongs.SB, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3660, "\"And that's just a theory, a Game Theory! Thanks for watching\""));
    public static final RegistryObject<Item> cassette_i_dont_wanna_be_free = ITEMS.register("cassette_i_dont_wanna_be_free", () -> new MMCassetteItem(8, MMSongs.IDWBF, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2860, "\"You're never livin' in prison theres always somethin to do!\""));
    public static final RegistryObject<Item> cassette_the_last_goodbye = ITEMS.register("cassette_the_last_goodbye", () -> new MMCassetteItem(8, MMSongs.THE_LAST_GOODBYE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3980, "\"We're going down in a blaze of glory!\""));
    public static final RegistryObject<Item> cassette_make_me_famous = ITEMS.register("cassette_make_me_famous", () -> new MMCassetteItem(8, MMSongs.MAKE_ME_FAMOUS, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3540, "\"ITS ENOUGH TO MAKE YOU THINK\""));
    public static final RegistryObject<Item> cassette_cosmic = ITEMS.register("cassette_cosmic", () -> new MMCassetteItem(8, MMSongs.COSMIC, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 9040, "None too far as we chase through the stars beyond forever, I'll follow you"));
    public static final RegistryObject<Item> cassette_mattel = ITEMS.register("cassette_mattel", () -> new MMCassetteItem(8, MMSongs.MATTEL, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 6620, "Advertisement, moral scrawl, a semblance of choice when there's no choice at all!"));
    public static final RegistryObject<Item> cassette_g = ITEMS.register("cassette_g", () -> new MMCassetteItem(8, MMSongs.G, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 4400, "Ahh fuck, give me a delete button..... Delete!"));
    public static final RegistryObject<Item> cassette_nightmare = ITEMS.register("cassette_nightmare", () -> new MMCassetteItem(8, MMSongs.NIGHTMARE, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 7440, "R.I.P - The Rev, world's best drummer."));
    public static final RegistryObject<Item> cassette_2_time_zones = ITEMS.register("cassette_2_time_zones", () -> new MMCassetteItem(8, MMSongs.TWO_TIME_ZONES, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 3240, "\"Because the clock idea was too good to pass up.\""));
    public static final RegistryObject<Item> cassette_pigstep = ITEMS.register("cassette_pigstep", () -> new MMCassetteItem(8, MMSongs.PIGSTEP, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 2920, "\"Interior Crocodile Aligator\""));
    public static final RegistryObject<Item> cassette_pigstep_jazz = ITEMS.register("cassette_pigstep_jazz", () -> new MMCassetteItem(8, MMSongs.PIGSTEP_JAZZ, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 7560, "The Piglins got classy."));
    public static final RegistryObject<Item> cassette_alpha = ITEMS.register("cassette_alpha", () -> new MMCassetteItem(8, MMSongs.ALPHA, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 12080, "Minecraft grew up with you."));
    public static final RegistryObject<Item> cassette_mov = ITEMS.register("cassette_mov", () -> new MMCassetteItem(8, MMSongs.MOV, new Item.Properties().tab(MMDiscTab.instance).stacksTo(1).rarity(Rarity.RARE), 5680, "\"The song you used to know.\""));

    //// Items
    public static final RegistryObject<Item> bull_pill = ITEMS.register("bull_pill", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(64).rarity(Rarity.RARE).food(FoodItems.bull_pill), "[TBD]"));
    public static final RegistryObject<MMPotionItem> agent_rainbow = ITEMS.register("agent_rainbow", () -> new MMPotionItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(16).rarity(Rarity.EPIC).food(FoodItems.agent_rainbow), "Easy access into the collective unconsious"));
    public static final RegistryObject<Item> airpod = ITEMS.register("airpod", () -> new MMCassetteItem(8, MMSongs.THEBEAST, new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.EPIC), 40,"\"fucking AIRPOD man he's so airpod and for what reason\""));
    public static final RegistryObject<Item> remnant = ITEMS.register("remnant", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(16).rarity(Rarity.COMMON), "\"Get ready for unstoppable fu-u-u-u-u-un, fun, fun.\""));
    public static final RegistryObject<Item> knob = ITEMS.register("knob", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(64).rarity(Rarity.COMMON), "Just 999 more!"));
    public static final RegistryObject<Item> joy_cons = ITEMS.register("joy_cons", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON), "JoyConBoyz For Life, Fly high Etika"));
    public static final RegistryObject<Item> drawing_tablet = ITEMS.register("drawing_tablet", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON), "My wrist hurts..."));
    public static final RegistryObject<Item> violin = ITEMS.register("violin", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON), "\"Steady your heartbeat.... Don't be afraid\""));
    public static final RegistryObject<Item> annoying_dog = ITEMS.register("annoying_dog", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON), "( The dog absorbs the cassette. )"));
    public static final RegistryObject<Item> gold_play_button = ITEMS.register("gold_play_button", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON), "[TBD]"));
    public static final RegistryObject<Item> normal_pills = ITEMS.register("normal_pills", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON), "\"You've become immune to my toxic fumes, my dose dependent presence.\""));
    public static final RegistryObject<Item> turron = ITEMS.register("turron", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON).food(FoodItems.turron), "\"Turr\u00F3n? Turr\u00F3n! Turr\u00F3n!\""));
    public static final RegistryObject<MMPotionItem> coffin_varnish = ITEMS.register("coffin_varnish", () -> new MMPotionItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON).food(FoodItems.coffin_varnish), "\"It beats radiator fluid\""));
    public static final RegistryObject<Item> stolas_grimoire = ITEMS.register("stolas_grimoire", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(1).rarity(Rarity.COMMON), "\"Jelly Sandwiches\""));
    public static final RegistryObject<Item> auric_bar = ITEMS.register("auric_bar", () -> new MMItem(new Item.Properties().tab(MMItemTab.instance).stacksTo(64).rarity(Rarity.COMMON), "Boundless power emanates from the metal"));
    public static final RegistryObject<Item> handsome_devil = ITEMS.register("handsome_devil", () -> new MMItem(new Item.Properties().stacksTo(1).rarity(Rarity.EPIC), "He is him. (Okami named this not Max)"));
    public static final RegistryObject<MMArmorItem> yeezys = ITEMS.register("yeezys", () -> new MMArmorItem(YeezyInfo.yeezys, EquipmentSlot.FEET, new Item.Properties().tab(MMItemTab.instance), "\"Shoe of the year\" - Kanye"));

    // TO SORT

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }

    public static class YeezyInfo {
        public static final ArmorMaterial yeezys = new ArmorMaterials("yeezys", 25, new int[] {2,2,2,2}, 9, SoundEvents.ARMOR_EQUIP_LEATHER, 0, 0, null);
    }

    public static class FoodItems {
        public static final FoodProperties bull_pill = new FoodProperties.Builder().nutrition(4).saturationMod(0.3f).alwaysEat().build();
        public static final FoodProperties agent_rainbow = new FoodProperties.Builder().nutrition(-4).saturationMod(-0.5f).alwaysEat().effect(() -> new MobEffectInstance(MobEffects.CONFUSION, 200, 3), 1.0f).build();
        public static final FoodProperties turron = new FoodProperties.Builder().nutrition(6).saturationMod(0.8f).build();
        public static final FoodProperties coffin_varnish = new FoodProperties.Builder().nutrition(-2).saturationMod(0.3f).alwaysEat().effect(() -> new MobEffectInstance(MobEffects.CONFUSION, 200, 3), 1.0f).build();
    }

}