package com.m4x4.mixtapes.sound;

import com.m4x4.mixtapes.maxs_mixtapes;
import net.minecraft.client.resources.sounds.Sound;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.common.util.ForgeSoundType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class MMSongs {
    public static final DeferredRegister<SoundEvent> SOUND_EVENTS =
            DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, maxs_mixtapes.MODID);

    public static final RegistryObject<SoundEvent> TEST_SOUND = registerSoundEvent("test_sound");
    public static final RegistryObject<SoundEvent> HCAS = registerSoundEvent("hcas");
    public static final RegistryObject<SoundEvent> DOLL_HOUSE = registerSoundEvent("doll_house");
    public static final RegistryObject<SoundEvent> BOTP = registerSoundEvent("botp");
    public static final RegistryObject<SoundEvent> IS_IT_ME = registerSoundEvent("is_it_me");
    public static final RegistryObject<SoundEvent> MATB = registerSoundEvent("matb");
    public static final RegistryObject<SoundEvent> WIT = registerSoundEvent("wit");
    public static final RegistryObject<SoundEvent> HISTE = registerSoundEvent("histe");
    public static final RegistryObject<SoundEvent> MY_ORDINARY_LIFE = registerSoundEvent("my_ordinary_life");
    public static final RegistryObject<SoundEvent> DRUNK = registerSoundEvent("drunk");
    public static final RegistryObject<SoundEvent> SSS = registerSoundEvent("sss");
    public static final RegistryObject<SoundEvent> FNAF = registerSoundEvent("fnaf");
    public static final RegistryObject<SoundEvent> FIVE_LONG_NIGHTS = registerSoundEvent("five_long_nights");
    public static final RegistryObject<SoundEvent> FMN = registerSoundEvent("fmn");
    public static final RegistryObject<SoundEvent> JUFAB = registerSoundEvent("jufab");
    public static final RegistryObject<SoundEvent> PARASITE = registerSoundEvent("parasite");
    public static final RegistryObject<SoundEvent> EISOP = registerSoundEvent("eisop");
    public static final RegistryObject<SoundEvent> DJMM = registerSoundEvent("djmm");
    public static final RegistryObject<SoundEvent> GOLFSWAMP = registerSoundEvent("golfswamp");
    public static final RegistryObject<SoundEvent> ROXANNE = registerSoundEvent("roxanne");
    public static final RegistryObject<SoundEvent> YCH = registerSoundEvent("ych");
    public static final RegistryObject<SoundEvent> ALWAYS_COME_BACK = registerSoundEvent("always_come_back");
    public static final RegistryObject<SoundEvent> LEAVE_ME_BEHIND = registerSoundEvent("leave_me_behind");
    public static final RegistryObject<SoundEvent> SANDCASTLE_KINGDOMS = registerSoundEvent("sandcastle_kingdoms");
    public static final RegistryObject<SoundEvent> BIG_POPPA = registerSoundEvent("big_poppa");
    public static final RegistryObject<SoundEvent> RFYL = registerSoundEvent("rfyl");
    public static final RegistryObject<SoundEvent> DOTD = registerSoundEvent("dotd");
    public static final RegistryObject<SoundEvent> GUIDING_LIGHT = registerSoundEvent("guiding_light");
    public static final RegistryObject<SoundEvent> HERE_I_COME = registerSoundEvent("here_i_come");
    public static final RegistryObject<SoundEvent> HERE_I_COME_2 = registerSoundEvent("here_i_come_2");
    public static final RegistryObject<SoundEvent> FBC = registerSoundEvent("fbc");
    public static final RegistryObject<SoundEvent> ARCHETYPE = registerSoundEvent("archetype");
    public static final RegistryObject<SoundEvent> BBT = registerSoundEvent("bbt");
    public static final RegistryObject<SoundEvent> BTD5 = registerSoundEvent("btd5");
    public static final RegistryObject<SoundEvent> GPS = registerSoundEvent("gps");
    public static final RegistryObject<SoundEvent> ROD = registerSoundEvent("rod");
    public static final RegistryObject<SoundEvent> IG = registerSoundEvent("ig");
    public static final RegistryObject<SoundEvent> FL = registerSoundEvent("fl");
    public static final RegistryObject<SoundEvent> ESC = registerSoundEvent("esc");
    public static final RegistryObject<SoundEvent> TOMCAT_DISPOSABLES = registerSoundEvent("tomcat_disposables");
    public static final RegistryObject<SoundEvent> WBTTA = registerSoundEvent("wbtta");
    public static final RegistryObject<SoundEvent> OKULTRA = registerSoundEvent("okultra");
    public static final RegistryObject<SoundEvent> LOVE_ME_NORMALLY = registerSoundEvent("love_me_normally");
    public static final RegistryObject<SoundEvent> PUPPETEER = registerSoundEvent("puppeteer");
    public static final RegistryObject<SoundEvent> BMP = registerSoundEvent("bmp");
    public static final RegistryObject<SoundEvent> PM = registerSoundEvent("pm");
    public static final RegistryObject<SoundEvent> TOACW = registerSoundEvent("toacw");
    public static final RegistryObject<SoundEvent> RETURN_TO_SLIME = registerSoundEvent("return_to_slime");
    public static final RegistryObject<SoundEvent> SOTU = registerSoundEvent("sotu");
    public static final RegistryObject<SoundEvent> UNIVERSAL_COLLAPSE = registerSoundEvent("universal_collapse");
    public static final RegistryObject<SoundEvent> JUNGLE_DRAGON = registerSoundEvent("jungle_dragon");
    public static final RegistryObject<SoundEvent> GHOSTS_N_STUFF = registerSoundEvent("ghosts_n_stuff");
    public static final RegistryObject<SoundEvent> BAD_END_THEATER = registerSoundEvent("bad_end_theater");
    public static final RegistryObject<SoundEvent> BARBIE_GIRL = registerSoundEvent("barbie_girl");
    public static final RegistryObject<SoundEvent> CALI_GIRLS = registerSoundEvent("cali_girls");
    public static final RegistryObject<SoundEvent> ANARCHY_RAINBOW = registerSoundEvent("anarchy_rainbow");
    public static final RegistryObject<SoundEvent> AMONGUS = registerSoundEvent("amongus");
    public static final RegistryObject<SoundEvent> FURRYMON = registerSoundEvent("furrymon");
    public static final RegistryObject<SoundEvent> EH = registerSoundEvent("eh");
    public static final RegistryObject<SoundEvent> TOTTFIY = registerSoundEvent("tottfiy");
    public static final RegistryObject<SoundEvent> GYMBATTLE = registerSoundEvent("gymbattle");
    public static final RegistryObject<SoundEvent> SG = registerSoundEvent("sg");
    public static final RegistryObject<SoundEvent> OOT = registerSoundEvent("oot");
    public static final RegistryObject<SoundEvent> ISLAND = registerSoundEvent("island");
    public static final RegistryObject<SoundEvent> POTM = registerSoundEvent("potm");
    public static final RegistryObject<SoundEvent> LOVE_LIKE_YOU = registerSoundEvent("love_like_you");
    public static final RegistryObject<SoundEvent> WILD_SIDE = registerSoundEvent("wild_side");
    public static final RegistryObject<SoundEvent> WAR = registerSoundEvent("war");
    public static final RegistryObject<SoundEvent> BOX15 = registerSoundEvent("box15");
    public static final RegistryObject<SoundEvent> BOX16 = registerSoundEvent("box16");
    public static final RegistryObject<SoundEvent> STILL_ALIVE = registerSoundEvent("still_alive");
    public static final RegistryObject<SoundEvent> WANT_YOU_GONE = registerSoundEvent("want_you_gone");
    public static final RegistryObject<SoundEvent> BETTY = registerSoundEvent("betty");
    public static final RegistryObject<SoundEvent> OTTT = registerSoundEvent("ottt");
    public static final RegistryObject<SoundEvent> CEST_LA_VIE = registerSoundEvent("cest_la_vie");
    public static final RegistryObject<SoundEvent> GOOD_MORNING = registerSoundEvent("good_morning");
    public static final RegistryObject<SoundEvent> STRONGER = registerSoundEvent("stronger");
    public static final RegistryObject<SoundEvent> AMERICAN_BOY = registerSoundEvent("american_boy");
    public static final RegistryObject<SoundEvent> GRAVITY = registerSoundEvent("gravity");
    public static final RegistryObject<SoundEvent> ADDICT = registerSoundEvent("addict");
    public static final RegistryObject<SoundEvent> COTTON_CANDY = registerSoundEvent("cotton_candy");
    public static final RegistryObject<SoundEvent> LAT = registerSoundEvent("lat");
    public static final RegistryObject<SoundEvent> YWBO = registerSoundEvent("ywbo");
    public static final RegistryObject<SoundEvent> SIMOON = registerSoundEvent("simoon");
    public static final RegistryObject<SoundEvent> GR = registerSoundEvent("gr");
    public static final RegistryObject<SoundEvent> ANEMOIA = registerSoundEvent("anemoia");
    public static final RegistryObject<SoundEvent> SUNSET_ROSE_COCKTAIL = registerSoundEvent("sunset_rose_cocktail");
    public static final RegistryObject<SoundEvent> OLIVE_BRANCH = registerSoundEvent("olive_branch");
    public static final RegistryObject<SoundEvent> RASPUTIN = registerSoundEvent("rasputin");
    public static final RegistryObject<SoundEvent> GOD_OF_WAR = registerSoundEvent("god_of_war");
    public static final RegistryObject<SoundEvent> THUNDER_ROLL = registerSoundEvent("thunder_roll");
    public static final RegistryObject<SoundEvent> MOS_THOSER = registerSoundEvent("mos_thoser");
    public static final RegistryObject<SoundEvent> TOXIC_COFFEE = registerSoundEvent("toxic_coffee");
    public static final RegistryObject<SoundEvent> VIRTUAL_INSANITY = registerSoundEvent("virtual_insanity");
    public static final RegistryObject<SoundEvent> DREAMLAND = registerSoundEvent("dreamland");
    public static final RegistryObject<SoundEvent> LIKE_THAT = registerSoundEvent("like_that");
    public static final RegistryObject<SoundEvent> FINAL_DUET = registerSoundEvent("final_duet");
    public static final RegistryObject<SoundEvent> HOME_FOR_FLOWERS = registerSoundEvent("home_for_flowers");
    public static final RegistryObject<SoundEvent> MY_TIME = registerSoundEvent("my_time");
    public static final RegistryObject<SoundEvent> UNDERTALE = registerSoundEvent("undertale");
    public static final RegistryObject<SoundEvent> DEATH_BY_GLAMOR = registerSoundEvent("death_by_glamor");
    public static final RegistryObject<SoundEvent> FOHAD = registerSoundEvent("fohad");
    public static final RegistryObject<SoundEvent> YCACH = registerSoundEvent("ycach");
    public static final RegistryObject<SoundEvent> SCARLET_FOREST = registerSoundEvent("scarlet_forest");
    public static final RegistryObject<SoundEvent> CYBERS_WORLD = registerSoundEvent("cybers_world");
    public static final RegistryObject<SoundEvent> SAFEANDSOUND = registerSoundEvent("safeandsound");
    public static final RegistryObject<SoundEvent> A_SAFE_WORLD = registerSoundEvent("a_safe_world");
    public static final RegistryObject<SoundEvent> SAC = registerSoundEvent("sac");
    public static final RegistryObject<SoundEvent> BM = registerSoundEvent("bm");
    public static final RegistryObject<SoundEvent> LETTER_TO_MY_BROTHER = registerSoundEvent("letter_to_my_brother");
    public static final RegistryObject<SoundEvent> AFTER_DARK = registerSoundEvent("after_dark");
    public static final RegistryObject<SoundEvent> MONSTER = registerSoundEvent("monster");
    public static final RegistryObject<SoundEvent> IJAM = registerSoundEvent("ijam");
    public static final RegistryObject<SoundEvent> FMTTM = registerSoundEvent("fmttm");
    public static final RegistryObject<SoundEvent> GTAW = registerSoundEvent("gtaw");
    public static final RegistryObject<SoundEvent> REJUV = registerSoundEvent("rejuv");
    public static final RegistryObject<SoundEvent> WMTAO = registerSoundEvent("wmtao");
    public static final RegistryObject<SoundEvent> BOW = registerSoundEvent("bow");
    public static final RegistryObject<SoundEvent> GHOST = registerSoundEvent("ghost");
    public static final RegistryObject<SoundEvent> WIGGLECORE = registerSoundEvent("wigglecore");
    public static final RegistryObject<SoundEvent> IF_WE_FALL = registerSoundEvent("if_we_fall");
    public static final RegistryObject<SoundEvent> KICK_BACK = registerSoundEvent("kick_back");
    public static final RegistryObject<SoundEvent> RIAV = registerSoundEvent("riav");
    public static final RegistryObject<SoundEvent> LIGHTSABERS = registerSoundEvent("lightsabers");
    public static final RegistryObject<SoundEvent> PIZZA_TIME = registerSoundEvent("pizza_time");
    public static final RegistryObject<SoundEvent> STREET_FIGHTER = registerSoundEvent("street_fighter");
    public static final RegistryObject<SoundEvent> SB = registerSoundEvent("sb");
    public static final RegistryObject<SoundEvent> IDWBF = registerSoundEvent("idwbf");
    public static final RegistryObject<SoundEvent> THE_LAST_GOODBYE = registerSoundEvent("the_last_goodbye");
    public static final RegistryObject<SoundEvent> COSMIC = registerSoundEvent("cosmic");
    public static final RegistryObject<SoundEvent> MATTEL = registerSoundEvent("mattel");
    public static final RegistryObject<SoundEvent> G = registerSoundEvent("g");
    public static final RegistryObject<SoundEvent> NIGHTMARE = registerSoundEvent("nightmare");
    public static final RegistryObject<SoundEvent> TWO_TIME_ZONES = registerSoundEvent("two_time_zones");
    public static final RegistryObject<SoundEvent> PIGSTEP = registerSoundEvent("pigstep");
    public static final RegistryObject<SoundEvent> PIGSTEP_JAZZ = registerSoundEvent("pigstep_jazz");
    public static final RegistryObject<SoundEvent> ALPHA = registerSoundEvent("alpha");
    public static final RegistryObject<SoundEvent> MOV = registerSoundEvent("mov");
    public static final RegistryObject<SoundEvent> VITAL = registerSoundEvent("vital");


    // Add Registry above
    private static RegistryObject<SoundEvent> registerSoundEvent(String name) {
        ResourceLocation id = new ResourceLocation(maxs_mixtapes.MODID, name);
        return SOUND_EVENTS.register(name, () -> new SoundEvent(id));
    }
    public static void register(IEventBus eventBus) {
        SOUND_EVENTS.register((eventBus));
    }
}
